<a href="https://colab.research.google.com/github/Kandy-541/Data-Science-and-Analytic/blob/main/Python_and_Pandas_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Data manipulating , coverage indexing, merging and reshaping a Sales dataset.

In [19]:
# import pandas
import pandas as pd

2. Upload and display dataset

In [20]:
# data upload
df = pd.read_csv('/sales_dataset.csv')

# data display
df.head()

,Customer_ID,Name,Region,Product,Quantity,Unit_Price,Payment_Method,Sales_Rep,Total_Sales
0,101,Alice,Buea,Laptop,2,450000,Mobile Money,Sona,900000
1,102,Brian,Limbe,Phone,1,250000,Cash,Kevin,250000
2,103,Chantal,Buea,Tablet,3,180000,Bank Transfer,Marlyse,540000
3,104,David,Douala,Laptop,1,450000,Mobile Money,Kevin,450000
4,105,Esther,Buea,Phone,2,250000,Cash,Sona,500000

3. Display last 5 rows

In [21]:
df.tail()

,Customer_ID,Name,Region,Product,Quantity,Unit_Price,Payment_Method,Sales_Rep,Total_Sales
7,108,Henry,Buea,Phone,4,250000,Cash,Kevin,1000000
8,109,Irene,Limbe,Laptop,1,450000,Mobile Money,Marlyse,450000
9,110,John,Douala,Tablet,3,180000,Bank Transfer,Sona,540000
10,111,Karen,Buea,Phone,2,250000,Cash,Kevin,500000
11,112,Louis,Douala,Laptop,1,450000,Mobile Money,Marlyse,450000

4. Check missing values

In [22]:
df.isnull().sum()

Customer_ID       0
Name              0
Region            0
Product           0
Quantity          0
Unit_Price        0
Payment_Method    0
Sales_Rep         0
Total_Sales       0
dtype: int64

In [23]:
# display dataframe
df

,Customer_ID,Name,Region,Product,Quantity,Unit_Price,Payment_Method,Sales_Rep,Total_Sales
0,101,Alice,Buea,Laptop,2,450000,Mobile Money,Sona,900000
1,102,Brian,Limbe,Phone,1,250000,Cash,Kevin,250000
2,103,Chantal,Buea,Tablet,3,180000,Bank Transfer,Marlyse,540000
3,104,David,Douala,Laptop,1,450000,Mobile Money,Kevin,450000
4,105,Esther,Buea,Phone,2,250000,Cash,Sona,500000
5,106,Frank,Limbe,Laptop,1,450000,Bank Transfer,Marlyse,450000
6,107,Grace,Douala,Tablet,2,180000,Mobile Money,Sona,360000
7,108,Henry,Buea,Phone,4,250000,Cash,Kevin,1000000
8,109,Irene,Limbe,Laptop,1,450000,Mobile Money,Marlyse,450000
9,110,John,Douala,Tablet,3,180000,Bank Transfer,Sona,540000
10,111,Karen,Buea,Phone,2,250000,Cash,Kevin,500000
11,112,Louis,Douala,Laptop,1,450000,Mobile Money,Marlyse,450000

5. Index customerID, name, region and product

In [24]:
df[['Customer_ID', 'Name', 'Region', 'Product']]

    Customer_ID     Name  Region Product
0           101    Alice    Buea  Laptop
1           102    Brian   Limbe   Phone
2           103  Chantal    Buea  Tablet
3           104    David  Douala  Laptop
4           105   Esther    Buea   Phone
5           106    Frank   Limbe  Laptop
6           107    Grace  Douala  Tablet
7           108    Henry    Buea   Phone
8           109    Irene   Limbe  Laptop
9           110     John  Douala  Tablet
10          111    Karen    Buea   Phone
11          112    Louis  Douala  Laptop

6. Select customers in Douala with product laptop and sales of 500,000

In [28]:
df[(df['Region']=='Douala') & (df['Product']=='laptop') & (df['Total_Sales']==500000)]

Empty DataFrame
Columns: [Customer_ID, Name, Region, Product, Quantity, Unit_Price, Payment_Method, Sales_Rep, Total_Sales]
Index: []

**the output above shows there's no data in such conditions**

7. Create dataframe for manager responsiblity

In [32]:
manager = pd.DataFrame({
    'Region': ['Buea', 'Limbe', 'Douala'],
    'Manager': ['Sona', 'Kevin', 'Marlyse']
})

# Display the new manager dataframe
display(manager)

   Region  Manager
0    Buea     Sona
1   Limbe    Kevin
2  Douala  Marlyse

8. Now, merge the newly created DataFrame

In [33]:
merge = pd.merge(df, manager, on='Region', how='left')

# display
merge.head()

,Customer_ID,Name,Region,Product,Quantity,Unit_Price,Payment_Method,Sales_Rep,Total_Sales,Manager
0,101,Alice,Buea,Laptop,2,450000,Mobile Money,Sona,900000,Sona
1,102,Brian,Limbe,Phone,1,250000,Cash,Kevin,250000,Kevin
2,103,Chantal,Buea,Tablet,3,180000,Bank Transfer,Marlyse,540000,Sona
3,104,David,Douala,Laptop,1,450000,Mobile Money,Kevin,450000,Marlyse
4,105,Esther,Buea,Phone,2,250000,Cash,Sona,500000,Sona

9. Calculate the total sales, quantity by region and products

In [37]:
# Quantity by region and products
df.pivot_table(index='Region', columns='Product', values=['Total_Sales','Quantity'], aggfunc='sum', fill_value=0)

        Quantity              Total_Sales
Product   Laptop Phone Tablet      Laptop    Phone  Tablet
Region
Buea           2     8      3      900000  2000000  540000
Douala         2     0      5      900000        0  900000
Limbe          2     1      0      900000   250000       0